DAYS_IN_MONTHLY_REPORT = 30
DAYS_IN_TWO_WEEKS_REPORT = 14
DAYS_IN_WEEK = 7
DATE_FORMAT = '%Y-%m-%d'

NPM_SEARCH_PREFIX = "@multiversx/sdk"
CRATES_SEARCH_PREFIX = "multiversx"
PYPI_SEARCH_PREFIX = "multiversx-sdk"

NPM_PAGE_SIZE = 20
CRATES_PAGE_SIZE = 20
GITHUB_SEARCH_PREFIX = "sdk"

GITHUB_ORGANIZATION = "multiversx"
