DAYS_IN_MONTHLY_REPORT = 30
DAYS_IN_TWO_WEEKS_REPORT = 14
DAYS_IN_WEEK = 7
DATE_FORMAT = '%Y-%m-%d'
DEFAULT_DATE = '1980-01-01'

GITHUB_OWN_ORGANIZATION = 'MULTIVERSX'

NPM_PAGE_SIZE = 20
CRATES_PAGE_SIZE = 20
GITHUB_PAGE_SIZE = 100

# HTTP
NO_OF_RETRIES = 10
SECONDS_BEFORE_RETRY = 10

BLUE_REPORT_PORT = 8050
GREEN_REPORT_PORT = 8051
YELLOW_REPORT_PORT = 8052

# PDF SAVE:
WAIT_FOR_RADIO_COMPONENT_LOAD = 1000
WAIT_FOR_TABS_COMPONENT_LOAD = 2000
WAIT_FOR_DROPDOWN_COMPONENT_LOAD = 1000

# ELASTIC SEARCH
LOG_URL = 'http://elastic-do-es-logs-02.elrond.ro:9200'
INDEX_NAME = "enriched-mainnet-access-*"
SCROLL_CONSISTENCY_TIME = "10m"
REQUEST_TIMEOUT = 600
SCAN_BATCH_SIZE = 7500
ELASTICSEARCH_MAX_RETRIES = 10
ELASTICSEARCH_CONNECTIONS_PER_NODE = 64
