DAYS_IN_MONTHLY_REPORT = 30
DAYS_IN_TWO_WEEKS_REPORT = 14
DAYS_IN_WEEK = 7
DATE_FORMAT = '%Y-%m-%d'
DEFAULT_DATE = '1980-01-01'

NPM_SEARCH_PREFIX = "@multiversx/sdk"
CRATES_SEARCH_PREFIX = "multiversx"
PYPI_SEARCH_PREFIX = "multiversx-sdk"
GITHUB_ORGANIZATION = "multiversx"
GITHUB_SEARCH_PREFIX = "sdk"

NPM_PAGE_SIZE = 20
CRATES_PAGE_SIZE = 20
GITHUB_PAGE_SIZE = 100

BLUE_REPORT_PORT = 8050
GREEN_REPORT_PORT = 8051
