DAYS_IN_MONTHLY_REPORT = 30
DAYS_IN_TWO_WEEKS_REPORT = 14
DAYS_IN_WEEK = 7
DATE_FORMAT = '%Y-%m-%d'
DEFAULT_DATE = '1980-01-01'

GITHUB_OWN_ORGANIZATION = 'MULTIVERSX'

NPM_PAGE_SIZE = 20
CRATES_PAGE_SIZE = 20
GITHUB_PAGE_SIZE = 100

BLUE_REPORT_PORT = 8050
GREEN_REPORT_PORT = 8051

GREEN_PDF_SAVE_WAIT_FOR_RADIO_COMPONENT_LOAD = 1000
GREEN_PDF_SAVE_WAIT_FOR_TABS_COMPONENT_LOAD = 2000
GREEN_PDF_SAVE_WAIT_FOR_DROPDOWN_COMPONENT_LOAD = 2000
BLUE_PDF_SAVE_WAIT_FOR_RADIO_COMPONENT_LOAD = 1000
BLUE_PDF_SAVE_WAIT_FOR_TABS_COMPONENT_LOAD = 2000
BLUE_PDF_SAVE_WAIT_FOR_DROPDOWN_COMPONENT_LOAD = 2000
